export const INTERESTS: string[] = [
  "Artificial Intelligence",
  "Web Development",
  "Mobile App Development",
  "Data Science",
  "Cybersecurity",
  "Robotics",
  "Blockchain",
  "Entrepreneurship",
  "Marketing",
  "Finance",
  "Public Speaking",
  "Creative Writing",
  "Graphic Design",
  "Music Production",
  "Photography",
  "Volunteering",
  "Gaming",
  "Sports Management",
  "Environmental Science",
  "Biotechnology",
  "Singing",
  "Dancing",
  "Cooking",
  "Drawing",
  "Painting",
  "Watching Movies",
  "Reading Books",
  "Journaling"
];

export const SKILLS: string[] = [
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "React",
  "Node.js",
  "SQL",
  "NoSQL",
  "Cloud Computing (AWS/GCP/Azure)",
  "Machine Learning",
  "Project Management",
  "Public Speaking",
  "Marketing",
  "Social Media Management",
  "Content Creation",
  "Graphic Design",
  "UI/UX Design",
  "Video Editing",
  "Sports",
  "Event Management",
  "Digital Marketing",
  "SEO/SEM",
  "Data Analysis",
  "Figma",
  "Adobe Creative Suite",
  "Leadership",
  "Teamwork",
  "Problem Solving"
];